name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: npm i
      - run: |
          nohup node services/api/server.mjs > server.log 2>&1 &
          sleep 2
          curl -s http://127.0.0.1:8081/api/health || (cat server.log && exit 1)
      - run: npm run test:smoke
      - run: npm run test:contract
